cat.js
This mainly removes the constraint around needing to enter an exact term when searching for an item. This is useful for partial searches (like `lea` matching `lead` and `leather`) but is mainly for the likely inconsistencies around plurals (one person adding `book`, another person adding `books`)
This also adds a minor feature where if the user accidentally leaves caps lock on while interacting with the bot - the bot will respond slightly differently.
=> Allow searching items by partial term

README.md, cat.js
As the branch name suggests this was intended to be a README but I ended up completely redoing how the bot is interacted with 🤷‍♂ 
**Was:**
`!cat add item: Books quantity: 32 price: 5 gold location: spawn`
`!cat search item: book`
`!cat update item: book price: 10 gold`
`!cat remove item: book`
**Now**
`!cat add 32 books:10 gold @spawn`
`!cat search book`
`!cat update -p book:10 gold`
`!cat remove book`
---
This also:
* Makes the command prefix just `!cat` - previously it would accept anything that _started_ with `!cat` but all examples use this, it's the easiest to type, and it's unaffected by locales
* Renamed internal arg values to be less specific - `item`, `price` becomes `primary`, `secondary`. This is because the old values aren't always accurate, especially with the new flag …
=> Add readme

commands/search.js
Discord messages are capped at 2,000 characters. Any more than this and the message will not send.
This is a problem when a catalogue query results in many lines. I cannot think of a good solution for this right now, but _a_ solution is to split the message up.
=> Work around for 2k char limit

cat.js, cat_modules/parse_input.js, cat_modules/query_from_flag.js, cat_modules/search_catalogue.js, commands/search.js, commands/update.js
I'm starting to think including '@' in the command wasn't a great idea. It makes adding items look quite cool, but '@' is already reserved for tagging a user.. so this may cause confusion.
Despite this, I've seen people searching for location with it, so instead of changing the way location is specified I've allowed searching by location with '@':
`!cat search @plot 1`
I've also tweaked the bot response message to include what it searched _by_:
```
Hi, Ty! That item search returned 1 result
Hi, Ty! That price search returned 1 result 
Hi, Ty! That location search returned 1 result 
Hi, Ty! That seller search returned 1 result 
```
I've also re-added the usage constraint for searching to require the primary argument, but explicitly allowed '*' to be a primary argument for when a wider …
=> Improve search

commands/update.js
This query was incorrectly converting the input to lowercase. This resulted in being unable to update any listings with capital letters in the name (e.g. `1 Book`)
=> Fix being unable to update a listing with caps in it

commands/remove.js
This query was incorrectly converting the input to lowercase. This resulted in being unable to remove any listings with capital letters in the name (e.g. 1 Book)
=> Fix being unable to remove a listing with caps in it

cat_modules/parse_input.js
I'm being a bit lazy when it comes to filtering input and should probably revisit it at some point to do it properly.
I see people using `’` instead of `'` and it's being filtered out. For now just add it to the list of 'safe' characters.
=> Allow a different type of apostrophe

commands/search.js
A location can be added to a listing for added detail, for example:
`[USER] is selling [ITEM] for [PRICE] at [LOCATION]`
I think this could be shortened. If location is specified then why not use it in place of the user? And if the location isn't specified then it'd be as it was anyway.
**Without**: `[USER] is selling [ITEM] for [PRICE]`
**With**: `[LOCATION] is selling [ITEM] for [PRICE]`
This may not work for locations that aren't a shop, but I've yet to see any listing location that isn't.
=> Tweak search output if location is present

cat.js, cat_modules/search_catalogue.js, commands/add.js, commands/remove.js, commands/search.js, commands/update.js, config.json.example
This allows certain users to remove anyone's listing.
If a Discord user ID is defined in the `admin_ids` list in the config, they will be able to remove any other user's listing. This is useful for admins to clear up stale listings from users who are no longer active.
=> Basic admin listing removal

.gitignore, commands/help.js, config.json.example, help.json.example
This bot was created for a Minecraft Discord server but the bot isn't specific to Minecraft. The only reference to MC exists in the help output.
This now instead uses whatever is defined in a file called `help.json`.
=> Remove embedded help information

cat.js, cat_modules/parse_input.js, commands/purge.js, commands/remove.js, commands/update.js
This changes updating and removing listings to use IDs instead of the wording of the listed item(s). This should make it easier to manage/understand. The downside to this, is that a user must know the ID in order to perform either of these actions, but the ID can be obtained via a detailed search.
One upside to this is bulk removal: `!cat remove 100, 101, 102`, for example would remove three listings with these IDs.
---
**Other changes**
* Fixed an issue where secondary values couldn't have spaces if a flag was present, so for example, updating a listings price with a multi-word value (e.g. "5 gold") would fail
* Tweaked bot response to unsuccessful commands
* Tidied up code slightly
=> Remove with ID

cat.js, cat_modules/admin_check.js, cat_modules/db.js, cat_modules/field_from_flag.js, cat_modules/parse_input.js, cat_modules/user.js, cat_modules/user_create.js, commands/add.js, commands/admin.js, commands/delete.js, commands/help.js, commands/purge.js, commands/remove.js, commands/search.js, commands/seller.js, commands/update.js, commands/users.js, config.json.example
Quite a few problems exist around users:
1. A username (seller) owns a listing
2. Usernames are used instead of nicknames in responses
3. Username is duplicated across however many listings they own
4. An admin is defined in a config file making adding/removing difficult
The solutions to these is to break out the user from listings into its own table. This new table would have fields such as: `discordId`, `name`, and `admin`. A user in this table would have many listings by association.
The Discord ID would own the listing, freeing up the `name` to be whatever the owner wants it to be. The name is purely for the listings, so it could be the Discord username, Discord server nickname, or in-game username, shop name, etc.
---
Other things will be included as part of this users table:
**Admin …
=> Add users table

commands/update.js
#33 changed it so that removing or updating a listing uses an ID instead of the text of the listing. It also added bulk removal using a comma-separated list of IDs.
There's no reason that same technique can't be applied to updating as well. If you wanted to update the price of three listings, and the IDs of those listings were `10`, `20`, `30`, you could do:
`!cat update -p 10, 20, 30 : 5 gold`
This may also fix a silent error when attempting to rename a listing to the same name as one that already exists.
=> Bulk update

README.md, cat_modules/responder.js, commands/user.js, config.json.example
Currently, only admins can add other admins which raises the obvious question - if there are no admins, how can one be made? This aims to solve that. The solution ins't ideal but it'll work for now given this isn't something that'll likely happen often.
The solution belongs in the config file - `adminDiscordId`. If this is defined, then running `!cat user makemeadmin` will take the Discord ID and make the user an admin.
This also adds `excludeFromHelp` to the sub-commands. If this is set to `true` in any sub-command then it will not appear in the command help.
This also updates the config example to include `status` and `statusType` which can be used to set the status of the bot. This was added in a previous commit but I forgot to update the example.
=> The first admin

cat_modules/db.js, commands/listing.js
Two problems:
1. When creating a DB for the first time it will error when creating the trigger because the table it is for doesn't "exist" at the time of creating it
2. `ON DELETE CASCADE` was not working. Purge depends on this, so purge does not work as expected
I've addressed the first by removing the trigger in favour of setting up `ON DELETE SET NULL`. This should do exactly what the trigger was created to do.
I've addressed the second by enabling PRAGMA FK which for some reason is turned off by default. This was never found in testing as I use a GUI to test DB stuff which has this PRAGMA enabled by default.
=> Enable PRAGMA FK, remove trigger

README.md, commands/listing.js, config.json.example
I've seen some confusion around listing searches. The current logic looks through listing names then through seller names and returns results in that order, but this in combination with the search cap meant that some stuff was getting buried without making search terms more specific to try and narrow it down further.
This updates search to only look through listings, and makes the search cap configurable.
=> Search only listings

cat_modules/db.js, commands/listing.js, commands/seller.js
Request to enable "suspending" a seller for a period of inactivity. It was agreed that the best approach would to be able to toggle it.
A seller can be made active/inactive with: `!cat seller toggle [:id]`
Listings of an inactive seller will not appear in search results but the seller can still be queried directly; this is open to change.
=> Toggle seller visibility

commands/listing.js
Regex was matching up until a word boundary, and would fail to match if a listing ended in a non-word character. This changes it to allow anything up until a colon but it cannot end with spaces.
=> Fix bot not recognising listings that end with a non-word character

README.md, commands/listing.js
Currently, a seller is specified in listing creation using `@[seller name]`. This wasn't a great decision as typing `@` in Discord, as it does in similar apps, will bring up a dropdown containing a list of people you may want to tag/mention. This makes things confusing.
This changes it to use `>` instead.
**Was:**
`!cat listing add item : price @shop`
**Now:**
`!cat listing add item : price > shop`
=> Change how sellers are specified when adding a listing

cat_modules/validator.js
Adds a check for number of "`:`" present in the command. This character is used as a separator and the presence of more than one will almost certainly result in the input being split incorrectly.
=> Disallow multiple colons

README.md, cat_modules/validator.js
"`:`" is used to handle inputs and a previous commit added a validation to prevent it from being used outside of where it was expected to be. The validation was simply checking if more than one colon was present in the input, but this isn't a good solution. One example of why it's not would be when adding a new seller - this command does not use a colon so one may be used as part of the seller name without the bot rejecting it, then when it comes to adding a listing to this seller - which does use a colon - the bot will reject it because there will be two colons in the input.
The second attempt to solve this involves running the check against the already separated/grouped args where the presence of any colons would result in rejection.
=> Improve disallowing the ":" character
